### GENERAL SETTINGS ###

# Site settings
title: hack-a-thon!
description: "Building a better Boise, by connecting volunteer developers and local not-for-profit organizations"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "https://boise-hack-a-thon.github.io/"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url:
  - title: facebook
    url:
  - title: twitter
    url:
  - title: instagram
    url:
  - title: tumblr
    url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:

email:
tel:


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Ben Kline
    position: Project Manager
    text: Ben is free lance developer in town is the a student at http://bloc.io.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:benkline@gmail.com
      - title: twitter
        url: http://twitter.com/boisebenkline
  - name: Richard Newman
    position: Director
    text:
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:richard@newmanworks.com
      - title: twitter
        url: http://twitter.com/rdnewman

# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: ""

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "There is just no other way that small, cash strapped organizations like mine would otherwise be able to share our stories. It is important that everyone, not matter what it is, deserve to have their story heard."
    author: Jessica Adams
    position: Counselor/Trainer - Growing up Gay in Idaho - http://www.jessica-adams.com
